det_conf: "./utils/table_transformer/src/detection_config.json"
det_model: "./utils/table_transformer/pubtables1m_detection_detr_r18.pth"
str_config: "./utils/table_transformer/src/structure_config.json"
str_model: "./utils/table_transformer/pubtables1m_structure_detr_r18.pth"
gemini_model_name: "gemini-1.5-flash"
deepseek_base_url: "https://api.deepseek.com"
deepseek_model: "deepseek-reasoner"
qdrant_collection_name: "annual_reports_trial_13_february"
vector_embedding_size: 3584
page_no: 0
page_text: 1
page_table: 2
embedding_model: "Alibaba-NLP/gte-Qwen2-7B-instruct"
qdrant_client_url: "http://127.0.0.1:6333"
log_dir: "./logs"
